=== ABDERRHMAN8BENAICHA/semi-structured-data-tps/TP2/task3.dtd
<!ELEMENT Class (Student+)>
<!ELEMENT Student (Name, Age, Grade)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Grade (#PCDATA)>
<!ATTLIST Student id CDATA #REQUIRED>

=== ABDERRHMAN8BENAICHA/semi-structured-data-tps/TP2/task3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Class SYSTEM "task3.dtd">


<Class>
    <Student id="1">
        <Name>John Doe</Name>
        <Age>20</Age>
        <Grade>Male</Grade>
    </Student>
    <Student id="2">
        <Name></Name>
        <Age>22</Age>
        <Grade>Male</Grade>
    </Student>
    <Student id="3">
        <Name></Name>
        <Age>19</Age>
        <Grade>Female</Grade>
    </Student>
    <Student id="4">
        <Name>Michael Brown</Name>
        <Age>21</Age>
        <Grade>Female</Grade>
    </Student>
</Class>
